import { signOut } from '@/features/auth/signOut'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Link from 'next/link'
import './globals.scss'

const montserrat = Montserrat({
	subsets: ['latin', 'cyrillic'],
	weight: ['400', '500', '600', '700', '800'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={montserrat.className}>
				<header>
					<h2>Next.js App</h2>
					<nav>
						<Link href='auth/login'>Войти</Link>
						<form action={signOut}>
							<button type='submit'>Выйти</button>
						</form>
					</nav>
				</header>
				<div className='container'>{children}</div>
			</body>
		</html>
	)
}
